# docker-compose -f docker-compose-be.yml up -d
# docker-compose -f docker-compose-be.yml down

services:
  # Servicio del Backend
  backend:
    image: oscarochoa01/mis-apis:0971bf5ce52c3a5b986d3996942e5b92c1378398
    container_name: age-detector-be
    ports:
      - "8081:8085"
    environment:
      # Configuración del servidor
      - PORT=8085

      # Configuración de MongoDB
      - MONGODB_URI=mongodb+srv://oscarochoar_db_user:LdJjGfQlThC2T7E8@cluster0.9pzkvjx.mongodb.net/?appName=Cluster0
      - MONGODB_DATABASE=age_detector_db

      # Configuración de RapidAPI
      - RAPIDAPI_KEY=99893ffdf7msha127d9eab43f25cp112bffjsnd3f5ded4cc44
      - RAPIDAPI_CHATGPT_URL=https://chatgpt-42.p.rapidapi.com/gpt4o
      - RAPIDAPI_CHATGPT_HOST=chatgpt-42.p.rapidapi.com
      - RAPIDAPI_IMAGE_URL=https://ai-text-to-image-generator-flux-free-api.p.rapidapi.com/aaaaaaaaaaaaaaaaaiimagegenerator/quick.php
      - RAPIDAPI_IMAGE_HOST=ai-text-to-image-generator-flux-free-api.p.rapidapi.com
    networks:
      - app-network
    restart: unless-stopped

  # Servicio del Frontend
  frontend:
    image: oscarochoa01/mis-apis-frontend:8eac1318bda2ab58de8e42c9240f81d85885c34a
    container_name: age-detector-fe
    ports:
      - "5000:80"
    environment:
      # URL del backend - cambiar según el entorno
      - VITE_API_BASE_URL=${BACKEND_URL:-http://localhost:8081/api}
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

# Red compartida para la comunicación entre servicios
networks:
  app-network:
    name: age-detector-network
    driver: bridge
