# docker-compose -f docker-compose-be.yml up -d
# docker-compose -f docker-compose-be.yml down

services:
  # Servicio de MongoDB
  mongodb:
    image: mongo:7.0
    container_name: age-detector-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: age_detector_db
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - my-network

  # Servicio del Backend
  backend:
    image: oscarochoa01/mis-apis:0971bf5ce52c3a5b986d3996942e5b92c1378398
    container_name: age-detector-be
    restart: unless-stopped
    ports:
      - "8085:8085"
    depends_on:
      - mongodb
    environment:
      # Configuración del servidor
      - PORT=8085
      - SERVER_URL=http://localhost:8085
      - SPRING_PROFILES_ACTIVE=dev
      
      # Configuración de MongoDB
      - MONGODB_URI=mongodb://admin:admin123@mongodb:27017/age_detector_db?authSource=admin
      - MONGODB_DATABASE=age_detector_db
      
      # Configuración de RapidAPI
      - RAPIDAPI_KEY=99893ffdf7msha127d9eab43f25cp112bffjsnd3f5ded4cc44
      - RAPIDAPI_CHATGPT_URL=https://chatgpt-42.p.rapidapi.com/gpt4o
      - RAPIDAPI_CHATGPT_HOST=chatgpt-42.p.rapidapi.com
      - RAPIDAPI_IMAGE_URL=https://ai-text-to-image-generator-flux-free-api.p.rapidapi.com/aaaaaaaaaaaaaaaaaiimagegenerator/quick.php
      - RAPIDAPI_IMAGE_HOST=ai-text-to-image-generator-flux-free-api.p.rapidapi.com
    networks:
      - my-network

# Volúmenes para persistir datos
volumes:
  mongodb_data:
    driver: local

# CREAR UNA RED EN ESTE COMPOSE PARA QUE SEA COMPARTIDA A FUTURO CON OTRO COMPOSE
networks:
  my-network:
    name: my-network
    driver: bridge
