# docker-compose -f docker-compose-be.yml up -d
# docker-compose -f docker-compose-be.yml down

services:
  # Servicio del Backend
  backend:
    image: oscarochoa01/mis-apis:0971bf5ce52c3a5b986d3996942e5b92c1378398
    container_name: age-detector-be
    ports:
      - "8085:8085"
    environment:
      # Configuración del servidor
      - PORT=8085
      
      # Configuración de MongoDB
      - MONGODB_URI=mongodb+srv://oscarochoar_db_user:LdJjGfQlThC2T7E8@cluster0.9pzkvjx.mongodb.net/?appName=Cluster0
      - MONGODB_DATABASE=age_detector_db
      
      # Configuración de RapidAPI
      - RAPIDAPI_KEY=99893ffdf7msha127d9eab43f25cp112bffjsnd3f5ded4cc44
      - RAPIDAPI_CHATGPT_URL=https://chatgpt-42.p.rapidapi.com/gpt4o
      - RAPIDAPI_CHATGPT_HOST=chatgpt-42.p.rapidapi.com
      - RAPIDAPI_IMAGE_URL=https://ai-text-to-image-generator-flux-free-api.p.rapidapi.com/aaaaaaaaaaaaaaaaaiimagegenerator/quick.php
      - RAPIDAPI_IMAGE_HOST=ai-text-to-image-generator-flux-free-api.p.rapidapi.com
    networks:
      - my-network

# CREAR UNA RED EN ESTE COMPOSE PARA QUE SEA COMPARTIDA A FUTURO CON OTRO COMPOSE
networks:
  my-network:
    name: my-network
    driver: bridge