# Configuración base
server:
  port: ${PORT:8085} # Valor por defecto si PORT no está configurado

spring:
  application:
    name: age-detector
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local} # Perfil por defecto
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false

# Variables personalizadas para APIs externas
rapidapi:
  key: ${RAPIDAPI_KEY}
  chatgpt:
    url: ${RAPIDAPI_CHATGPT_URL}
    host: ${RAPIDAPI_CHATGPT_HOST}
  image-generator:
    url: ${RAPIDAPI_IMAGE_URL}
    host: ${RAPIDAPI_IMAGE_HOST}

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
